export const DUMMYOFFERS = [
    {
        CANTIDAD: 20,
        DESCRIPCION: "Semillas secas",
        FECHACADUCIDAD: "2024-05-19T17:01:41.000Z",
        ID: 1,
        NOMBRE: "Semillas de Maíz",
        OFERTADOR: "Freddy Anaya",
        PRECIO: 1000,
        TIPO: "Insumo",
    },
    {
        CANTIDAD: 5,
        DESCRIPCION: "Frutas frescas",
        FECHACADUCIDAD: "2022-05-19T17:01:41.000Z",
        ID: 2,
        NOMBRE: "Manzanas",
        OFERTADOR: "Pedro Pérez",
        PRECIO: 3000,
        TIPO: "Producto",
    },
    {
        CANTIDAD: 3,
        DESCRIPCION: "Hortalizas frescas",
        FECHACADUCIDAD: "2022-05-19T17:01:41.000Z",
        ID: 3,
        NOMBRE: "Lechuga",
        OFERTADOR: "Juan Pérez",
        PRECIO: 1000,
        TIPO: "Producto",
    },
    {
        CANTIDAD: 10,
        DESCRIPCION: "Semillas secas",
        FECHACADUCIDAD: "2024-05-19T17:01:41.000Z",
        ID: 4,
        NOMBRE: "Semillas de Frijol",
        OFERTADOR: "Freddy Anaya",
        PRECIO: 1000,
        TIPO: "Insumo",
    },
    {
        CANTIDAD: 1,
        DESCRIPCION: "Frutas frescas",
        FECHACADUCIDAD: "2022-05-19T17:01:41.000Z",
        ID: 5,
        NOMBRE: "Pera",
        OFERTADOR: "Pedro Pérez",
        PRECIO: 3000,
        TIPO: "Producto",
    },
    {
        CANTIDAD: 5,
        DESCRIPCION: "Hortalizas frescas",
        FECHACADUCIDAD: "2022-05-19T17:01:41.000Z",
        ID: 6,
        NOMBRE: "Cebolla",
        OFERTADOR: "Juan Pérez",
        PRECIO: 1000,
        TIPO: "Producto",
    },
    {
        CANTIDAD: 10,
        DESCRIPCION: "Semillas secas",
        FECHACADUCIDAD: "2024-05-19T17:01:41.000Z",
        ID: 7,
        NOMBRE: "Semillas de Trigo",
        OFERTADOR: "Freddy Anaya",
        PRECIO: 1000,
        TIPO: "Insumo",
    },
    {
        CANTIDAD: 5,
        DESCRIPCION: "Frutas frescas",
        FECHACADUCIDAD: "2022-05-19T17:01:41.000Z",
        ID: 8,
        NOMBRE: "Mango",
        OFERTADOR: "Pedro Pérez",
        PRECIO: 3000,
        TIPO: "Producto",
    },
    {
        CANTIDAD: 5,
        DESCRIPCION: "Hortalizas frescas",
        FECHACADUCIDAD: "2022-05-19T17:01:41.000Z",
        ID: 9,
        NOMBRE: "Tomate",
        OFERTADOR: "Juan Pérez",
        PRECIO: 1000,
        TIPO: "Producto",
    },
    {
        CANTIDAD: 10,
        DESCRIPCION: "Semillas secas",
        FECHACADUCIDAD: "2024-05-19T17:01:41.000Z",
        ID: 10,
        NOMBRE: "Semillas de Ajonjolí",
        OFERTADOR: "Freddy Anaya",
        PRECIO: 1000,
        TIPO: "Insumo",
    },
    {
        CANTIDAD: 5,
        DESCRIPCION: "Frutas frescas",
        FECHACADUCIDAD: "2022-05-19T17:01:41.000Z",
        ID: 11,
        NOMBRE: "Banano",
        OFERTADOR: "Pedro Pérez",
        PRECIO: 3000,
        TIPO: "Producto",
    },    
    {
        CANTIDAD: 5,
        DESCRIPCION: "Hortalizas frescas",
        FECHACADUCIDAD: "2022-05-19T17:01:41.000Z",
        ID: 12,
        NOMBRE: "Pepino",
        OFERTADOR: "Juan Pérez",
        PRECIO: 1000,
        TIPO: "Producto",
    },
    {
        CANTIDAD: 10,
        DESCRIPCION: "Semillas secas",
        FECHACADUCIDAD: "2024-05-19T17:01:41.000Z",
        ID: 13,
        NOMBRE: "Semillas de Calabaza",
        OFERTADOR: "Freddy Anaya",
        PRECIO: 1000,
        TIPO: "Insumo",
    },
    {
        CANTIDAD: 5,
        DESCRIPCION: "Frutas frescas",
        FECHACADUCIDAD: "2022-05-19T17:01:41.000Z",
        ID: 14,
        NOMBRE: "Naranja",
        OFERTADOR: "Pedro Pérez",
        PRECIO: 3000,
        TIPO: "Producto",
    },
    {
        CANTIDAD: 5,
        DESCRIPCION: "Hortalizas frescas",
        FECHACADUCIDAD: "2022-05-19T17:01:41.000Z",
        ID: 15,
        NOMBRE: "Zanahoria",
        OFERTADOR: "Juan Pérez",
        PRECIO: 1000,
        TIPO: "Producto",
    },
    {
        CANTIDAD: 10,
        DESCRIPCION: "Semillas secas",
        FECHACADUCIDAD: "2024-05-19T17:01:41.000Z",
        ID: 16,
        NOMBRE: "Semillas de Chía",
        OFERTADOR: "Freddy Anaya",
        PRECIO: 1000,
        TIPO: "Insumo",
    },    
];