CREATE OR REPLACE PACKAGE PAQ_FETCH IS

PROCEDURE GET_MUNICIPIOS;
PROCEDURE GET_USUARIO(
    P_USUID IN USUARIO.USUID%TYPE
);
PROCEDURE GET_OFERTAS(
    PATTERN IN STRING
);
PROCEDURE GET_OFERTAS(
    P_USUID IN USUARIO.USUID%TYPE,
    PATTERN IN STRING
);
PROCEDURE GET_OFERTAS;
PROCEDURE GET_PRODUCTOS;

END PAQ_FETCH;

-- IMPLEMENTACION DEL PAQUETE
CREATE OR REPLACE PACKAGE BODY PAQ_FETCH IS

PROCEDURE GET_MUNICIPIOS IS
    RC SYS_REFCURSOR;
BEGIN
    OPEN rc FOR SELECT * FROM MUNICIPIO ORDER BY MUNNOMBRE;
    DBMS_SQL.RETURN_RESULT(rc);    
END GET_MUNICIPIOS;

PROCEDURE GET_USUARIO(
    P_USUID IN USUARIO.USUID%TYPE
) IS
    RC SYS_REFCURSOR;
BEGIN
    OPEN rc FOR SELECT * FROM USUARIO WHERE USUID = P_USUID;
    DBMS_SQL.RETURN_RESULT(rc);    
END GET_USUARIO;

PROCEDURE GET_OFERTAS(
    PATTERN IN STRING
) IS
    RC SYS_REFCURSOR;
BEGIN
    OPEN rc FOR SELECT * FROM V_OFERTAS WHERE DESCRIPCION LIKE '%' || PATTERN || '%';
    DBMS_SQL.RETURN_RESULT(rc);    
END GET_OFERTAS;

PROCEDURE GET_OFERTAS(
    P_USUID IN USUARIO.USUID%TYPE,
    PATTERN IN STRING
) IS
    RC SYS_REFCURSOR;
BEGIN
    OPEN rc FOR SELECT * FROM V_OFERTAS WHERE USUID = P_USUID AND DESCRIPCION LIKE '%' || PATTERN || '%';
    DBMS_SQL.RETURN_RESULT(rc);    
END GET_OFERTAS;

PROCEDURE GET_OFERTAS IS
    RC SYS_REFCURSOR;
BEGIN
    OPEN rc FOR SELECT * FROM V_OFERTAS;
    DBMS_SQL.RETURN_RESULT(rc);    
END GET_OFERTAS;

PROCEDURE GET_PRODUCTOS IS
    RC SYS_REFCURSOR;
BEGIN
    OPEN rc FOR SELECT * FROM PRODUCTO;
    DBMS_SQL.RETURN_RESULT(rc);    
END GET_PRODUCTOS;

END PAQ_FETCH; -- PACKAGE end